version: '3.9'

services:
  postgres:
    build: .
    environment:
      POSTGRES_DB: ipsenh
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ../:/ipsenh_research
      - postgres:/data/postgres

volumes:
  postgres:
